from __future__ import annotations


def instructions() -> str:
    return (
        "You are analyzing code to understand and map system architecture. "
        "For each code chunk, perform deep architectural analysis:\n\n"
        "1. **Component Identification**\n"
        "   - What system layer is this? (API/presentation, business logic, data access, infrastructure, utilities)\n"
        "   - What specific component/module does it represent?\n"
        "   - What is its primary responsibility?\n\n"
        "2. **Dependencies & Relationships**\n"
        "   - What does it depend on? (imports, calls to other modules, external services)\n"
        "   - What depends on it? (who calls this, who uses this)\n"
        "   - Are there circular dependencies?\n\n"
        "3. **Interfaces & Contracts**\n"
        "   - What public API does it expose? (HTTP endpoints, public methods, events, message queues)\n"
        "   - What are the input/output contracts? (request/response formats, parameters, return types)\n"
        "   - What protocols does it implement? (REST, WebSocket, gRPC, message patterns)\n\n"
        "4. **Data Flow**\n"
        "   - How does data enter this component?\n"
        "   - How is data transformed?\n"
        "   - Where does data go next? (database, cache, external API, downstream services)\n"
        "   - What data structures are central? (models, DTOs, entities)\n\n"
        "5. **Design Patterns & Principles**\n"
        "   - What design patterns are used? (factory, repository, strategy, observer, dependency injection, etc.)\n"
        "   - How is separation of concerns achieved?\n"
        "   - Is SOLID followed? Any violations?\n\n"
        "6. **Scaling & Performance Considerations**\n"
        "   - What are the bottlenecks? (blocking I/O, heavy computation, database queries)\n"
        "   - How does it handle concurrency? (locks, async/await, thread pools)\n"
        "   - What caching strategies are used?\n\n"
        "7. **Configuration & Environment**\n"
        "   - What configuration does it need? (environment variables, config files)\n"
        "   - How does it differ between environments? (dev/staging/prod)\n\n"
        "For follow_up_queries, suggest:\n"
        "- Related components that should be examined together\n"
        "- Missing pieces of the architecture (e.g., 'Where is authentication handled?')\n"
        "- Entry points not yet discovered (e.g., 'Find all API route definitions')\n\n"
        "Output: Provide architectural insights that help build a complete system diagram. "
        "Be specific about file paths, class names, function names, and relationships between components."
    )
