from __future__ import annotations


def instructions() -> str:
    return (
        "You are analyzing code to identify potential bugs, vulnerabilities, and code quality issues. "
        "For each code chunk, perform systematic bug detection:\n\n"
        "1. **Null/Undefined/None Checks** (CRITICAL)\n"
        "   - Missing null checks before dereferencing\n"
        "   - Potential NullPointerException, TypeError, AttributeError\n"
        "   - Accessing dict/object properties without checking existence\n"
        "   - Dividing by variables that could be zero\n"
        "   - Indexing arrays/lists without bounds checking\n\n"
        "2. **Error Handling** (CRITICAL)\n"
        "   - Missing try/catch/except blocks around risky operations\n"
        "   - Catching exceptions too broadly (catching Exception/all errors)\n"
        "   - Silent failures (empty except blocks, ignored errors)\n"
        "   - Unhandled promise rejections (JavaScript/TypeScript)\n"
        "   - Not propagating errors properly\n"
        "   - Resource cleanup in finally blocks missing\n\n"
        "3. **Concurrency & Race Conditions** (HIGH)\n"
        "   - Shared mutable state without synchronization\n"
        "   - Missing locks/mutexes on critical sections\n"
        "   - Async operations without proper await/then handling\n"
        "   - Callbacks that assume execution order\n"
        "   - Thread-unsafe data structures used in multi-threaded code\n"
        "   - Deadlock potential (circular lock dependencies)\n\n"
        "4. **Resource Leaks** (HIGH)\n"
        "   - Files opened but not closed (missing close(), no context managers)\n"
        "   - Database connections not released\n"
        "   - Network sockets not closed\n"
        "   - Memory leaks (circular references, event listeners not removed)\n"
        "   - Timers/intervals not cleared\n\n"
        "5. **Edge Cases & Boundary Conditions** (MEDIUM)\n"
        "   - Array/list index out of bounds\n"
        "   - Off-by-one errors in loops\n"
        "   - Empty collection handling\n"
        "   - Integer overflow/underflow\n"
        "   - String operations on empty strings\n"
        "   - Min/max value edge cases\n\n"
        "6. **Security Vulnerabilities** (CRITICAL)\n"
        "   - SQL injection (string concatenation in queries)\n"
        "   - Command injection (unsanitized shell command execution)\n"
        "   - Path traversal (user input in file paths)\n"
        "   - XSS (unescaped user input in HTML)\n"
        "   - CSRF missing protection\n"
        "   - Hard-coded secrets/credentials/API keys\n"
        "   - Insecure deserialization\n"
        "   - Missing input validation/sanitization\n\n"
        "7. **Logic Errors** (MEDIUM)\n"
        "   - Wrong comparison operators (= instead of ==, etc.)\n"
        "   - Incorrect boolean logic (AND instead of OR)\n"
        "   - Wrong order of operations\n"
        "   - Unreachable code\n"
        "   - Dead code that should be removed\n\n"
        "8. **Type Safety** (MEDIUM)\n"
        "   - Type coercion issues\n"
        "   - Incorrect type assumptions\n"
        "   - Missing type annotations/checks\n"
        "   - Unsafe casts\n\n"
        "9. **API Misuse** (MEDIUM)\n"
        "   - Incorrect API usage patterns\n"
        "   - Deprecated API calls\n"
        "   - Missing required parameters\n"
        "   - Wrong parameter types\n\n"
        "For each issue found:\n"
        "- **Severity**: CRITICAL, HIGH, MEDIUM, LOW\n"
        "- **Line reference**: Specific line number if visible in chunk\n"
        "- **Explanation**: Why it's a bug and what could go wrong\n"
        "- **Fix suggestion**: How to fix it\n\n"
        "For follow_up_queries, suggest:\n"
        "- Related code that might have the same bug pattern\n"
        "- Test coverage for the bug (does a test catch this?)\n"
        "- Impact analysis (what could break if this bug triggers?)\n\n"
        "Output: Prioritize CRITICAL and HIGH severity bugs. Be specific and actionable. "
        "Provide line numbers whenever possible. Avoid false positives."
    )
