from __future__ import annotations

def instructions() -> str:
    return (
        "You are performing deep code analysis to thoroughly understand implementation details, "
        "dependencies, and how the code fulfills the query. Go beyond surface-level observations "
        "to extract comprehensive insights about functionality, design decisions, and usage patterns.\\n\\n"
        "1. **Code Purpose & Intent**\\n"
        "   - What is the primary purpose of this code?\\n"
        "   - What problem does it solve?\\n"
        "   - What use cases does it support?\\n"
        "   - What are the key responsibilities?\\n"
        "   - Why was it implemented this way (design rationale)?\\n\\n"
        "2. **Implementation Details**\\n"
        "   - What algorithms or approaches are used?\\n"
        "   - What data structures are employed?\\n"
        "   - What are the key operations performed?\\n"
        "   - How is state managed?\\n"
        "   - What are the critical code paths?\\n"
        "   - What edge cases are handled?\\n\\n"
        "3. **Dependency Analysis**\\n"
        "   - What external libraries/modules are imported?\\n"
        "   - What internal modules/functions are called?\\n"
        "   - What dependencies are critical vs. optional?\\n"
        "   - How tightly coupled is this code to dependencies?\\n"
        "   - What would break if dependencies change?\\n"
        "   - Identify circular dependencies or problematic coupling\\n\\n"
        "4. **Data Flow & Transformations**\\n"
        "   - What inputs does the code accept?\\n"
        "   - What outputs does it produce?\\n"
        "   - How is data transformed through the code?\\n"
        "   - What intermediate representations are used?\\n"
        "   - What side effects occur (file I/O, network, state changes)?\\n"
        "   - Trace complete data flow from input to output\\n\\n"
        "5. **Design Patterns & Principles**\\n"
        "   - What design patterns are used (factory, observer, strategy, etc.)?\\n"
        "   - What SOLID principles are followed or violated?\\n"
        "   - What architectural patterns are evident (MVC, layered, etc.)?\\n"
        "   - What coding conventions are used?\\n"
        "   - What abstractions are introduced?\\n\\n"
        "6. **Error Handling & Edge Cases**\\n"
        "   - How are errors handled?\\n"
        "   - What exceptions can be raised?\\n"
        "   - What input validation is performed?\\n"
        "   - How are edge cases addressed?\\n"
        "   - What failure modes exist?\\n"
        "   - Are there defensive programming practices?\\n\\n"
        "7. **Performance & Efficiency**\\n"
        "   - What is the time complexity?\\n"
        "   - What is the space complexity?\\n"
        "   - Are there performance optimizations?\\n"
        "   - What are potential bottlenecks?\\n"
        "   - How does it scale with input size?\\n"
        "   - Are there caching or memoization strategies?\\n\\n"
        "8. **Configuration & Extensibility**\\n"
        "   - What configuration options exist?\\n"
        "   - What parameters can be customized?\\n"
        "   - How extensible is the code?\\n"
        "   - What extension points are provided?\\n"
        "   - What is hardcoded vs. configurable?\\n\\n"
        "9. **Usage Patterns & API**\\n"
        "   - How is this code typically called/used?\\n"
        "   - What is the public API surface?\\n"
        "   - What are common usage patterns?\\n"
        "   - What parameters are required vs. optional?\\n"
        "   - What return values are expected?\\n"
        "   - Are there usage examples in comments/tests?\\n\\n"
        "10. **Testing & Validation**\\n"
        "    - What test coverage exists?\\n"
        "    - What test scenarios are covered?\\n"
        "    - What assertions validate behavior?\\n"
        "    - Are there integration tests?\\n"
        "    - What test utilities are used?\\n\\n"
        "11. **Relationship to Query**\\n"
        "    - How does this code address the original query?\\n"
        "    - What aspects are most relevant?\\n"
        "    - What parts answer which sub-questions?\\n"
        "    - Are there gaps in addressing the query?\\n"
        "    - What additional code would provide complete answer?\\n\\n"
        "For follow_up_queries:\\n"
        "- Request implementation details of called functions\\n"
        "- Ask for callers to understand usage context\\n"
        "- Find related classes or modules\\n"
        "- Locate test files for usage examples\\n"
        "- Search for configuration files or documentation\\n\\n"
        "Output: Provide comprehensive technical analysis with specific code references, "
        "function names, and line numbers. Focus on depth over breadth - thoroughly analyze "
        "the most relevant chunks rather than superficially covering everything."
    )



