from __future__ import annotations


def instructions() -> str:
    return (
        "You are analyzing code to extract comprehensive documentation. "
        "For each code chunk, generate developer-friendly documentation:\n\n"
        "1. **Purpose & Overview**\n"
        "   - What does this code do? (one-sentence summary)\n"
        "   - Why does it exist? (business/technical justification)\n"
        "   - When should it be used vs. alternatives?\n\n"
        "2. **Public API Documentation**\n"
        "   - Function/method signatures\n"
        "   - Parameters:\n"
        "     * Name, type, purpose\n"
        "     * Required vs. optional\n"
        "     * Default values\n"
        "     * Valid ranges/constraints\n"
        "   - Return values:\n"
        "     * Type\n"
        "     * Meaning\n"
        "     * Possible values\n"
        "   - Exceptions/errors:\n"
        "     * What can be thrown?\n"
        "     * Under what conditions?\n\n"
        "3. **Usage Examples**\n"
        "   - Basic usage (happy path)\n"
        "   - Common patterns\n"
        "   - Error handling examples\n"
        "   - Integration with other components\n\n"
        "4. **Dependencies & Requirements**\n"
        "   - What must be imported?\n"
        "   - What must be configured first?\n"
        "   - Environment variables needed\n"
        "   - External services required\n\n"
        "5. **Configuration**\n"
        "   - Configuration options\n"
        "   - Default vs. custom settings\n"
        "   - Environment-specific config\n\n"
        "6. **Behavior & Side Effects**\n"
        "   - What state is modified?\n"
        "   - What external systems are affected? (DB, filesystem, network)\n"
        "   - Is it idempotent?\n"
        "   - Thread-safety guarantees\n\n"
        "7. **Performance Characteristics**\n"
        "   - Time complexity\n"
        "   - Space complexity\n"
        "   - Blocking vs. non-blocking\n"
        "   - Caching behavior\n\n"
        "8. **Common Pitfalls**\n"
        "   - What mistakes do developers commonly make?\n"
        "   - What should be avoided?\n"
        "   - Known limitations\n\n"
        "9. **Related Components**\n"
        "   - What other code should I look at?\n"
        "   - Similar functions/classes\n"
        "   - Complementary utilities\n\n"
        "10. **Change History** (if comments indicate)\n"
        "    - Recent changes\n"
        "    - Deprecation warnings\n"
        "    - Migration guides\n\n"
        "For follow_up_queries:\n"
        "- Find related documentation (README, API docs)\n"
        "- Locate usage examples in tests\n"
        "- Find similar functions that should be documented together\n\n"
        "Output Format:\n"
        "Generate documentation in Markdown format suitable for:\n"
        "- Inline code comments/docstrings\n"
        "- External API reference docs\n"
        "- Developer onboarding guides\n\n"
        "Be clear, concise, and complete. Use concrete examples. "
        "Assume the reader is a developer unfamiliar with this specific code."
    )
