from __future__ import annotations


def instructions() -> str:
    return (
        "You are performing exploratory analysis to map the codebase broadly and discover "
        "key areas of interest. Take a breadth-first approach to surface important patterns, "
        "concerns, and areas that warrant deeper investigation.\\n\\n"
        "1. **High-Level Overview**\\n"
        "   - What is the overall purpose of this codebase area?\\n"
        "   - What major components or subsystems exist?\\n"
        "   - What are the primary responsibilities?\\n"
        "   - What are the most important files/modules?\\n"
        "   - What patterns or themes are evident?\\n\\n"
        "2. **Key Modules & Components**\\n"
        "   - What are the central modules?\\n"
        "   - What does each module handle?\\n"
        "   - What are the main entry points?\\n"
        "   - What components interact frequently?\\n"
        "   - Which modules are foundational vs. peripheral?\\n\\n"
        "3. **Cross-Cutting Concerns**\\n"
        "   - What concerns span multiple modules (logging, error handling, validation)?\\n"
        "   - What patterns are repeated across the codebase?\\n"
        "   - What shared utilities or helpers exist?\\n"
        "   - What common dependencies are used everywhere?\\n"
        "   - What conventions are followed consistently?\\n\\n"
        "4. **Important Relationships**\\n"
        "   - What are the main data flows?\\n"
        "   - What modules depend on each other?\\n"
        "   - What are the critical integration points?\\n"
        "   - How do components communicate?\\n"
        "   - What are the key abstractions?\\n\\n"
        "5. **Areas of Interest**\\n"
        "   - What code looks complex or important?\\n"
        "   - What areas have high coupling or dependencies?\\n"
        "   - What functionality appears central to the system?\\n"
        "   - What code is likely to change frequently?\\n"
        "   - What areas might have hidden complexity?\\n\\n"
        "6. **Surprising or Notable Findings**\\n"
        "   - What is unexpected or unusual?\\n"
        "   - What design choices stand out?\\n"
        "   - What code deviates from typical patterns?\\n"
        "   - What functionality is more complex than expected?\\n"
        "   - What areas seem under-documented?\\n\\n"
        "7. **Technology & Tools**\\n"
        "   - What frameworks or libraries are used?\\n"
        "   - What third-party dependencies are critical?\\n"
        "   - What language features are heavily used?\\n"
        "   - What development tools are evident (testing, build)?\\n"
        "   - What external services are integrated?\\n\\n"
        "8. **Code Quality Indicators**\\n"
        "   - What is the overall code organization quality?\\n"
        "   - What areas have good documentation?\\n"
        "   - What areas lack documentation?\\n"
        "   - What is the test coverage like?\\n"
        "   - What code smells are evident?\\n\\n"
        "For follow_up_queries:\\n"
        "- Deep dive into complex or high-impact modules\\n"
        "- Investigate surprising or unusual patterns\\n"
        "- Search for implementations of key functionality\\n"
        "- Find all usages of critical components\\n"
        "- Locate related code in other modules\\n\\n"
        "Output Format:\\n"
        "- Start with a high-level summary of findings\\n"
        "- List key modules and their purposes\\n"
        "- Highlight areas that warrant further investigation\\n"
        "- Note surprising or high-impact discoveries\\n"
        "- Provide specific file paths and component names\\n"
        "- Prioritize breadth over depth - cover more ground rather than deep analysis"
    )
