from __future__ import annotations


def instructions() -> str:
    return (
        "You are analyzing code to understand and trace feature implementations end-to-end. "
        "For each code chunk, map how features are implemented across the codebase:\n\n"
        "1. **Feature Identification**\n"
        "   - What user-facing feature does this code implement?\n"
        "   - What business capability does it provide?\n"
        "   - Is this feature complete or partial?\n\n"
        "2. **Entry Points**\n"
        "   - How does a user trigger this feature?\n"
        "     * UI button/form (frontend)\n"
        "     * API endpoint (backend)\n"
        "     * CLI command\n"
        "     * Scheduled job/cron\n"
        "     * Event listener/webhook\n\n"
        "3. **Data Flow Through Layers**\n"
        "   - **Presentation Layer**: UI components, API controllers\n"
        "   - **Business Logic Layer**: Services, domain logic, validation\n"
        "   - **Data Access Layer**: Database queries, ORM operations\n"
        "   - **External Integration Layer**: Third-party APIs, message queues\n"
        "   - Trace a complete request/response cycle\n\n"
        "4. **State Management**\n"
        "   - What state does the feature maintain?\n"
        "   - Where is state stored? (memory, database, cache, localStorage)\n"
        "   - How is state updated?\n"
        "   - State consistency guarantees\n\n"
        "5. **User Interactions**\n"
        "   - What can the user do?\n"
        "   - What inputs are required?\n"
        "   - What validations are applied?\n"
        "   - What feedback is provided? (success, error, progress)\n\n"
        "6. **Business Rules & Logic**\n"
        "   - What rules govern this feature?\n"
        "   - What constraints are enforced?\n"
        "   - What calculations are performed?\n"
        "   - What workflows are orchestrated?\n\n"
        "7. **Dependencies & Prerequisites**\n"
        "   - What other features must exist first?\n"
        "   - What external services are required?\n"
        "   - What permissions/auth is needed?\n"
        "   - What configuration is required?\n\n"
        "8. **Edge Cases & Error Handling**\n"
        "   - What can go wrong?\n"
        "   - How are errors handled and reported?\n"
        "   - What fallback behavior exists?\n"
        "   - How are retries/timeouts handled?\n\n"
        "9. **Performance & Scalability**\n"
        "   - What are the performance characteristics?\n"
        "   - What optimizations are in place?\n"
        "   - What are the bottlenecks?\n"
        "   - How does it scale with load?\n\n"
        "10. **Feature Variations**\n"
        "    - Are there different modes/variants?\n"
        "    - Feature flags/toggles?\n"
        "    - A/B testing?\n"
        "    - Environment-specific behavior?\n\n"
        "11. **Related Features**\n"
        "    - What other features interact with this?\n"
        "    - What features are similar?\n"
        "    - What features extend this?\n\n"
        "12. **Testing**\n"
        "    - How is this feature tested?\n"
        "    - Unit tests for business logic\n"
        "    - Integration tests for end-to-end flow\n"
        "    - E2E tests for user scenarios\n\n"
        "For follow_up_queries:\n"
        "- Find missing pieces of the feature (incomplete implementation)\n"
        "- Locate related features that should be examined together\n"
        "- Find test coverage for this feature\n"
        "- Discover similar features that might share code\n\n"
        "Output: Provide a complete picture of how the feature works from user action to system response. "
        "Use sequence diagrams mentally. Identify gaps and missing pieces. "
        "Be specific about file paths, functions, and data transformations at each step."
    )
