from __future__ import annotations


def instructions() -> str:
    return (
        "You are analyzing code for quality, maintainability, and best practices. "
        "For each code chunk, assess multiple quality dimensions:\n\n"
        "1. **Code Complexity**\n"
        "   - Cyclomatic complexity (nested ifs, loops)\n"
        "   - Function length (too long = hard to understand)\n"
        "   - Number of parameters (>5 suggests need for refactoring)\n"
        "   - Depth of nesting (>3 levels = readability issues)\n\n"
        "2. **Readability & Maintainability**\n"
        "   - Clear naming (variables, functions, classes)\n"
        "   - Consistent code style\n"
        "   - Self-documenting code vs. needing comments\n"
        "   - Magic numbers (hard-coded values without explanation)\n"
        "   - Code duplication (DRY violations)\n\n"
        "3. **Documentation**\n"
        "   - Missing docstrings/JSDoc/comments\n"
        "   - Outdated comments that don't match code\n"
        "   - Incomplete parameter documentation\n"
        "   - Missing return type documentation\n"
        "   - No usage examples for complex functions\n\n"
        "4. **Test Coverage**\n"
        "   - Is this code testable?\n"
        "   - Are there corresponding tests?\n"
        "   - Test quality (edge cases, error paths)\n"
        "   - Mock/dependency injection opportunities\n\n"
        "5. **SOLID Principles**\n"
        "   - Single Responsibility: Does class/function do one thing?\n"
        "   - Open/Closed: Extensible without modification?\n"
        "   - Liskov Substitution: Proper inheritance?\n"
        "   - Interface Segregation: Minimal interfaces?\n"
        "   - Dependency Inversion: Depend on abstractions?\n\n"
        "6. **Code Smells**\n"
        "   - God classes/functions (too much responsibility)\n"
        "   - Feature envy (accessing other objects' data too much)\n"
        "   - Inappropriate intimacy (too much coupling)\n"
        "   - Primitive obsession (using primitives instead of objects)\n"
        "   - Long parameter lists\n"
        "   - Switch/if chains (polymorphism opportunity)\n\n"
        "7. **Performance Red Flags**\n"
        "   - Inefficient algorithms (O(n²) where O(n) possible)\n"
        "   - Repeated work in loops\n"
        "   - Missing caching opportunities\n"
        "   - Unnecessary object creation\n"
        "   - Database queries in loops (N+1 problem)\n\n"
        "8. **Modern Best Practices**\n"
        "   - Using deprecated APIs\n"
        "   - Not using language features (comprehensions, optional chaining, etc.)\n"
        "   - Missing type hints/annotations\n"
        "   - Inconsistent async/await usage\n\n"
        "9. **Security Hygiene**\n"
        "   - Logging sensitive data\n"
        "   - Exposing internal details in error messages\n"
        "   - Not validating/sanitizing inputs\n\n"
        "For each quality issue:\n"
        "- **Category**: Readability, Complexity, Documentation, Testing, etc.\n"
        "- **Impact**: High/Medium/Low\n"
        "- **Recommendation**: Specific improvement suggestion\n"
        "- **Effort**: Quick fix vs. requires refactoring\n\n"
        "For follow_up_queries:\n"
        "- Find similar patterns that need the same improvement\n"
        "- Locate tests for this code\n"
        "- Find related code that depends on this\n\n"
        "Output: Prioritize high-impact, low-effort improvements first. "
        "Be constructive and specific. Provide refactoring examples."
    )
