from __future__ import annotations

def instructions() -> str:
    return (
        "You are analyzing code structure to understand how modules, classes, functions, and "
        "components are organized. Focus on code organization, relationships, hierarchies, and "
        "the overall structure of the implementation.\\n\\n"
        "1. **Module & Package Structure**\\n"
        "   - What modules/packages are present?\\n"
        "   - How are modules organized into packages?\\n"
        "   - What is the directory/file hierarchy?\\n"
        "   - What naming conventions are used?\\n"
        "   - Are there __init__.py files and what do they expose?\\n"
        "   - What is the module dependency tree?\\n\\n"
        "2. **Class Hierarchy & Relationships**\\n"
        "   - What classes are defined?\\n"
        "   - What inheritance hierarchies exist?\\n"
        "   - What interfaces/abstract classes are defined?\\n"
        "   - What are the parent-child relationships?\\n"
        "   - Are there mixin classes or composition patterns?\\n"
        "   - What are the key class responsibilities?\\n\\n"
        "3. **Function & Method Organization**\\n"
        "   - What are the main functions/methods?\\n"
        "   - How are functions grouped (by class, module, purpose)?\\n"
        "   - What are helper vs. core functions?\\n"
        "   - What functions are standalone vs. methods?\\n"
        "   - What is the call hierarchy?\\n"
        "   - What are the most frequently called functions?\\n\\n"
        "4. **Public API Surface**\\n"
        "   - What functions/classes are exported/public?\\n"
        "   - What is in __all__ declarations?\\n"
        "   - What are the main entry points?\\n"
        "   - What interfaces are exposed to users?\\n"
        "   - What parameters do public functions accept?\\n"
        "   - How is the API documented?\\n\\n"
        "5. **Internal Structure**\\n"
        "   - What private/internal functions exist (_prefixed)?\\n"
        "   - What helper classes support the main functionality?\\n"
        "   - What utility modules are present?\\n"
        "   - What internal data structures are used?\\n"
        "   - How is internal state managed?\\n\\n"
        "6. **Code Organization Patterns**\\n"
        "   - Are related functions grouped together?\\n"
        "   - Is there separation of concerns?\\n"
        "   - What layering exists (data, logic, presentation)?\\n"
        "   - Are there factory functions or builders?\\n"
        "   - How are constants and configuration organized?\\n\\n"
        "7. **Dependency Relationships**\\n"
        "   - What modules import what?\\n"
        "   - What are the dependency chains?\\n"
        "   - Are there circular dependencies?\\n"
        "   - What modules are most depended upon?\\n"
        "   - What external dependencies are used?\\n"
        "   - What is the dependency graph structure?\\n\\n"
        "8. **Component Boundaries**\\n"
        "   - How is the code divided into components?\\n"
        "   - What are the boundaries between components?\\n"
        "   - What interfaces connect components?\\n"
        "   - What data flows between components?\\n"
        "   - Are components loosely or tightly coupled?\\n\\n"
        "9. **Code Size & Complexity**\\n"
        "   - How many lines per file/class/function?\\n"
        "   - What is the cyclomatic complexity?\\n"
        "   - What are the largest/most complex components?\\n"
        "   - Are there any overly large files (>500 lines)?\\n"
        "   - What is the nesting depth?\\n\\n"
        "For follow_up_queries:\\n"
        "- Find all subclasses of a given class\\n"
        "- Locate all callers of a function\\n"
        "- Search for all implementations of an interface\\n"
        "- Find related modules or components\\n"
        "- Identify all public API functions\\n\\n"
        "Output Format:\\n"
        "- Provide a hierarchical overview of the structure\\n"
        "- List classes with their methods and relationships\\n"
        "- Identify entry points and main functions\\n"
        "- Show dependency relationships\\n"
        "- Use specific file paths, class names, and function names\\n"
        "- Focus on organization and relationships rather than implementation details"
    )
