from __future__ import annotations


def instructions() -> str:
    return (
        "You are creating a concise, clear summary of code that captures the essential information "
        "needed to understand and use it. Focus on clarity, brevity, and practical utility.\\n\\n"
        "1. **Purpose & Responsibility**\\n"
        "   - What is the primary purpose in one sentence?\\n"
        "   - What problem does this code solve?\\n"
        "   - What is it responsible for?\\n"
        "   - When would someone use this?\\n\\n"
        "2. **Main Entry Points**\\n"
        "   - What are the primary functions/classes to use?\\n"
        "   - What is the public API?\\n"
        "   - What are the most common usage patterns?\\n"
        "   - What parameters do key functions take?\\n\\n"
        "3. **How to Use It**\\n"
        "   - What is a typical usage example?\\n"
        "   - What are the required vs. optional parameters?\\n"
        "   - What does it return or produce?\\n"
        "   - What setup or configuration is needed?\\n"
        "   - What are common use cases?\\n\\n"
        "4. **Key Components**\\n"
        "   - What are the 3-5 most important classes/functions?\\n"
        "   - What does each one do (one line each)?\\n"
        "   - How do they relate to each other?\\n\\n"
        "5. **Dependencies & Requirements**\\n"
        "   - What external libraries are required?\\n"
        "   - What other modules does it depend on?\\n"
        "   - What are the prerequisites for using it?\\n\\n"
        "6. **Important Details**\\n"
        "   - What are the key constraints or limitations?\\n"
        "   - What edge cases should users be aware of?\\n"
        "   - What common mistakes should be avoided?\\n"
        "   - What performance considerations exist?\\n\\n"
        "7. **Relationship to Query**\\n"
        "   - How does this code answer the original query?\\n"
        "   - What aspects are most relevant to the question?\\n"
        "   - What key points address the user's needs?\\n\\n"
        "For follow_up_queries:\\n"
        "- Request usage examples or test cases\\n"
        "- Find related documentation\\n"
        "- Locate configuration files\\n"
        "- Search for integration points\\n\\n"
        "Output Format:\\n"
        "- Start with a one-sentence summary\\n"
        "- Use bullet points for clarity\\n"
        "- Keep each point to 1-2 lines maximum\\n"
        "- Avoid implementation details unless critical\\n"
        "- Focus on what users need to know, not how it works internally\\n"
        "- Be specific with function names and file paths\\n"
        "- Prioritize clarity and usability over completeness"
    )
